### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by AndrewRayCode** [react-grid-layout/react-draggable#107]
```
user@~ $ mkdir drag-test

user@~ $ cd drag-test/

user@~/drag-test $ npm install react-draggable
    react-draggable@1.0.1 node_modules/react-draggable
    ├── object-assign@4.0.1
    └── classnames@2.2.0

user@~/drag-test $ node
    > var d = require('react-draggable')
    Error: Cannot find module 'react'
```

Unless I'm missing something, you appear to be confused about what `devDependencies` are vs `dependencies` in [package.json](https://github.com/mzabriskie/react-draggable/blob/master/package.json#L48).

**Comment by STRML** [comment]
No, I am not - modules that are dependent on React usually use them as `peerDependencies`, because loading two versions of React breaks an application. I chose to omit peerDeps in this project because I've seen endless upgrade problems in React applications due to too-restrictive version ranges.

You couldn't actually use this in a project without having React already installed, so your example above is contrived.

**Comment by AndrewRayCode** [comment]
```
user@~ $ mkdir drag-test

user@~ $ cd drag-test/

user@~/drag-test $ npm install react-draggable react
react-draggable@1.0.1 node_modules/react-draggable
├── object-assign@4.0.1
└── classnames@2.2.0

react@0.14.1 node_modules/react
├── envify@3.4.0 (through@2.3.8, jstransform@10.1.0)
└── fbjs@0.3.2 (whatwg-fetch@0.9.0, ua-parser-js@0.7.9, loose-envify@1.1.0, promise@7.0.4, core-js@1.2.4)

user@~/drag-test $ node
> require('react-draggable')
Error: Cannot find module 'react-dom'
```

?

**Comment by STRML** [comment]
You have to install react-dom in 0.14.
https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#two-packages-react-and-react-dom
