### ISSUE TITLE
Place within bounds on initial draw

### ISSUE THREAD

**Issue by spaasis** [react-grid-layout/react-draggable#189]
Would it be possible to snap an uncontrolled Draggable to its bounds when the component is initialized? Currently it is possible to initialize a Draggable outside its bounds, which causes the component to jump around when first moved.

The context for this issue is that I have a map with a Draggable legend, which has a defaultPosition (user defined). When the view port gets small enough (for example embedding) the legend gets placed way outside of the main view port. If the bounds were checked in the initialization phase, the legend would always be visible on the map, no matter the size of the view.

**Comment by STRML** [comment]
This isn't possible; components can't access their context in the DOM before mounting. I can't possibly know where I'll be placed in the tree, thus I can't measure margin or padding.

Consider compensating for the margin/padding yourself by passing the sum in as `defaultPosition`, or otherwise add a time delay opacity animation to hide the snap.
