### ISSUE TITLE
Textarea rendered inside draggable divs are not working.

### ISSUE THREAD

**Issue by sourav-kumar** [react-grid-layout/react-draggable#289]
I have wrapped a textarea with draggable component, after rendering on the browser its not editable.
Any way we can make textarea editable ?

**Comment by this-miguel** [comment]
Hello from Venezuela :) I have this same issue, do you have any news about it? did you manage to solve the problem?

**Comment by this-miguel** [comment]
hey I noticed that <Draggable> has a prop called `disable`  when is `true` you can type inside the inputs, but you will not be able to drag, so you may play with it to suit your needs

**Comment by this-miguel** [comment]
Hey!, pass `enableUserSelectHack:false` as a prop to the `Draggable` component and you will be able to use the input fields, like this `<Draggable enableUserSelectHack={false}>`

**Comment by sourav-kumar** [comment]
Earlier I used `disable` to make the textarea editable, but `enableUserSelectHack:false` attribute worked well for me.

Thank you very much for your help.

**Comment by bstst** [comment]
Why isn't this documented? It just saved me a ton of headache after a couple of days of headbanging.

**Comment by STRML** [comment]
Why not submit a doc PR?

**Comment by bstst** [comment]
The name of the property "enableUserSelectHack" makes me think IF this should at all be documented, as it most obviously is a hack.

That's why I'm asking the question — is this a hack, as in a "hack"? Why is this a hack? Should anyone attempt at documenting it? Should anyone attempt to submit a PR that would make this property unnecessary? So many questions, you see!

Thus, it's more of a _request-to-discuss-this_.

**Comment by STRML** [comment]
Yeah I call it a hack because it's something I wish we didn't have to do - dragging and holding the mouse btn down selects text all of the page, so we inject some CSS to disable that.

I don't see any way around it, although we have refined it somewhat over the years. If it could be made to *not* apply to children of the draggable that might fix the issue.

**Comment by awongCM** [comment]
Hi there!

Just out of curiosity, I recently imported this library into one of my pet React projects.  My use case for it is, simply,  you are able to drag any UI components has embedded form input fields to be editable.  

Initially, I struggled for some time in getting this behaviour to work; lost a number of hours in the midst of frustration.. until I read this issue tag (and, finally, got it to work!)

Based on your comments above @STRML, are you suggesting that this hack might be resolved at some distant future?  Or do you think it's okay to leave it as it is? I'm curious to know your long term thoughts behind this..

I really enjoy using this plugin as it comes with simple API abstractions, which caters all the basic and common needs I want for my own React Apps.  There's another library, [react-dnd](https://github.com/react-dnd/react-dnd), which is great also.  A lot of community support behind them.  However, it's got Redux baked in already, and I don't need something that's overly-complex for building simple react apps unless I need better control of managing states in greater depth, upfront.

Hence, my firm thought is that I'm hoping you'll continue to support this library; so that I don't have to resign myself in using other complex drag-n-drop react libraries out there in case this library run into other unexpected issues when building them.

Thanks!

**Comment by Meesam** [comment]
@this-miguel :- perfact, its working

**Comment by dcorb** [comment]
Solved with the "cancel" prop? #314

**Comment by OlivierJM** [comment]
@this-miguel your hack solved it for me too. Thanks
