### ISSUE TITLE
How to get the x %

### ISSUE THREAD

**Issue by IndigoBee** [react-grid-layout/react-draggable#408]
I'm trying to make a slider button and I don't see how to find the position.x % I'm in compared ton the parent.

![image](https://user-images.githubusercontent.com/33088396/59155633-915c8d00-8a96-11e9-8417-4b53fbe78295.png)

```javascript
onControlledDragStop = (e, position) => {
    console.log(position); // I only receive lastX and X which are always the same. Delta X is always 0
    this.onControlledDrag(e, position);
  };
```

**Comment by STRML** [comment]
Hi. This is not a bug with the library - try StackOverflow.

**Comment by franznkemaka** [comment]
Hi 

just had the same issue and for any dev wondering how to solve this: 

Yeah, it isn't a bug. The problem is that **onStop** gets fired with the last **onDrag** params: That makes sense because the user stopped dragging at the same spot of the last drag. 

To overcome this issue, one has to record the **onStart** position and compare it at the **onStop**. The difference is the drag change.


```javascript
onStart = (e, position) => {
 // log the position with a ref for example if you use React Hooks
lastPositionRef.current = position;
}

onStop = (e, position) => {
// compare the position or calculate the delta

const deltaX = position.x - (lastPositionRef.current.x || 0);
const deltaY = position.y - (lastPositionRef.current.y || 0);
}
```
